/**
 * C++ header generation: each waveform emitted as an inline `int16_t` array.
 */
import { DecodedWave } from "./decodeROM";

function arrayName(prefix: string, waveformIndex: number): string {
  return `${prefix}_${String(waveformIndex).padStart(3, "0")}`;
}

function formatArray(values: ArrayLike<number>): string {
  const rows: string[] = [];
  const perRow = 16;
  for (let i = 0; i < values.length; i += perRow) {
    const row: number[] = [];
    for (let j = i; j < Math.min(i + perRow, values.length); j++) row.push(values[j]);
    rows.push("    " + row.join(", ") + (i + perRow < values.length ? "," : ""));
  }
  return rows.join("\n");
}

export interface HeaderOptions {
  /** Which sample field to emit: 16-bit scaled, or the true 12-bit range. */
  which: "samples16" | "samples12";
  /** C++ namespace to wrap everything in. */
  namespaceName: string;
  /** Prefix for each per-wave array name. */
  arrayPrefix: string;
  /** Name of the pointer table + count constant. */
  tableName: string;
  /** Free-form provenance text placed in the header comment block. */
  provenance: string;
}

export function buildCppHeader(waves: DecodedWave[], opts: HeaderOptions): string {
  const guard = `${opts.namespaceName.toUpperCase()}_${opts.which.toUpperCase()}_H_`;
  const lines: string[] = [];

  lines.push(`// Auto-generated by prophet-vs-wavetable-converter. Do not edit by hand.`);
  lines.push(`//`);
  for (const line of opts.provenance.split("\n")) lines.push(`// ${line}`);
  lines.push(``);
  lines.push(`#ifndef ${guard}`);
  lines.push(`#define ${guard}`);
  lines.push(``);
  lines.push(`#include <cstdint>`);
  lines.push(`#include <cstddef>`);
  lines.push(``);
  lines.push(`namespace ${opts.namespaceName} {`);
  lines.push(``);

  for (const wave of waves) {
    const name = arrayName(opts.arrayPrefix, wave.waveformIndex);
    const values = wave[opts.which];
    lines.push(`// waveform index ${wave.waveformIndex} (ROM table offset ${wave.romIndex})`);
    lines.push(`inline constexpr int16_t ${name}[${values.length}] = {`);
    lines.push(formatArray(values));
    lines.push(`};`);
    lines.push(``);
  }

  lines.push(`inline constexpr int${opts.arrayPrefix === "" ? "" : ""} ${opts.tableName}Count = ${waves.length};`);
  lines.push(`inline constexpr int ${opts.tableName}WaveformIndex[${waves.length}] = {`);
  lines.push(formatArray(waves.map((w) => w.waveformIndex)));
  lines.push(`};`);
  lines.push(`inline constexpr const int16_t* const ${opts.tableName}[${waves.length}] = {`);
  lines.push(
    waves
      .map((w, i) => {
        const name = arrayName(opts.arrayPrefix, w.waveformIndex);
        return "    " + name + (i + 1 < waves.length ? "," : "");
      })
      .join("\n")
  );
  lines.push(`};`);
  lines.push(``);
  lines.push(`}  // namespace ${opts.namespaceName}`);
  lines.push(``);
  lines.push(`#endif  // ${guard}`);
  lines.push(``);

  return lines.join("\n");
}
