// Names are sourced from:
// https://forum.sequential.com/index.php?topic=120.0
// https://themusicalsynthesizer.wordpress.com/2017/07/08/evolver-digital-wave-shape-descriptions/

export const waveformNames = [
 { pvs: "Sine", evolver: "Sine" },
 { pvs: "Saw", evolver: "Sawtooth" },
 { pvs: "Sqr", evolver: "Square" },
 { pvs: "WmBell", evolver: "WmBell" },
 { pvs: "RdBell", evolver: "RdBell" },
 { pvs: "R2Bell", evolver: "R2Bell" },
 { pvs: "W2Bell", evolver: "W2Bell" },
 { pvs: "FmtBell", evolver: "FmtBell" },
 { pvs: "FzReed", evolver: "FzReed" },
 { pvs: "FmtAOh", evolver: "FmtAOh" },
 { pvs: "FmtAhh", evolver: "FmtAhh" },
 { pvs: "TriPlus", evolver: "TriPlus" },
 { pvs: "DisBel", evolver: "DisBel" },
 { pvs: "Pulse1", evolver: "Pulse 1" },
 { pvs: "Pulse2", evolver: "Pulse 2" },
 { pvs: "SqrReed", evolver: "Square Reed" },
 { pvs: "Oohh", evolver: "Oohh" },
 { pvs: "Eehh", evolver: "Eehh" },
 { pvs: "FeedBack", evolver: "FeedBack" },
 { pvs: "Piano1", evolver: "Piano1" },
 { pvs: "E.Pno", evolver: "Electric Piano" },
 { pvs: "M.Harm", evolver: "M.Harm" },
 { pvs: "HiTop", evolver: "HiTop" },
 { pvs: "WmReed", evolver: "WmReed" },
 { pvs: "3 & 5", evolver: "3rd and 5th harmonics; fundamental absent" },
 { pvs: "Hollow", evolver: "Hollow" },
 { pvs: "Hvy7", evolver: "Heavy 7th harmonics" },
 { pvs: "BelOrg", evolver: "BelOrg" },
 { pvs: "BassBel", evolver: "BASSBELL (14th and 28th harmonics)" },
 { pvs: "Tine1", evolver: "Tine1" },
 { pvs: "PhSQR", evolver: "PhSQR" },
 { pvs: "Orient", evolver: "Orient" },
 { pvs: "HiPipe", evolver: "HiPipe" },
 { pvs: "Mass", evolver: "Mass" },
 { pvs: "ReedOrg", evolver: "ReedOrg" },
 { pvs: "OrgAhh", evolver: "OrgAhh" },
 { pvs: "MelOrg", evolver: "MelOrg" },
 { pvs: "FmtOrg", evolver: "FmtOrg" },
 { pvs: "Clar", evolver: "Clarinet" },
 { pvs: "AhhFem", evolver: "AhhFem" },
 { pvs: "AhhHom", evolver: "AhhHom" },
 { pvs: "AhhBass", evolver: "AhhBass" },
 { pvs: "RegVox", evolver: "RegVox" },
 { pvs: "Vocal", evolver: "VOCAL 1 (Detune oscs using either wave to bring out the vocal)" },
 { pvs: "Homme", evolver: "VOCAL 2 (Detune oscs using either wave to bring out the vocal)" },
 { pvs: "HiAhh", evolver: "HiAhh" },
 { pvs: "Bass", evolver: "Bass" },
 { pvs: "Guitar", evolver: "Guitar" },
 { pvs: "Nice", evolver: "Nice" },
 { pvs: "WWind", evolver: "WoodWind" },
 { pvs: "Oboe", evolver: "Oboe" },
 { pvs: "Harp", evolver: "Harp" },
 { pvs: "Pipe", evolver: "Pipe" },
 { pvs: "Hack1", evolver: "Hack1" },
 { pvs: "Hack2", evolver: "Hack2" },
 { pvs: "Hack3", evolver: "Hack3" },
 { pvs: "Pinch", evolver: "Pinch" },
 { pvs: "BellHrm", evolver: "BellHrm" },
 { pvs: "BellVox", evolver: "BellVox" },
 { pvs: "Hi Harm", evolver: "Hi Harm" },
 { pvs: "Hi Reed", evolver: "Hi Reed" },
 { pvs: "BellReed", evolver: "BellReed" },
 { pvs: "WmWhstl", evolver: "WmWhstl" },
 { pvs: "Wood", evolver: "Wood" },
 { pvs: "Pure", evolver: "Pure" },
 { pvs: "Med Pure", evolver: "Med Pure" },
 { pvs: "HiHarm", evolver: "HiHarm" },
 { pvs: "FullBell", evolver: "FullBell" },
 { pvs: "Bell", evolver: "Bell" },
 { pvs: "Pinch", evolver: "Pinch" },
 { pvs: "Clustr", evolver: "Clustr" },
 { pvs: "M.Pinch", evolver: "M.Pinch" },
 { pvs: "VoxPnch", evolver: "VoxPnch" },
 { pvs: "OrgPnch", evolver: "OrgPnch" },
 { pvs: "AhhPnch", evolver: "AhhPnch" },
 { pvs: "PnoOrg", evolver: "PnoOrg" },
 { pvs: "BrReed", evolver: "BrReed" },
 { pvs: "NoFund", evolver: "NoFund" },
 { pvs: "ReedHrm", evolver: "ReedHrm" },
 { pvs: "LiteFund", evolver: "LiteFund" },
 { pvs: "MelOrg", evolver: "MelOrg" },
 { pvs: "Bell", evolver: "Bell Partials 1" },
 { pvs: "Bell", evolver: "Bell" },
 { pvs: "3&5Saw", evolver: "Sawtooth 3rd and 5th" },
 { pvs: "5thSin", evolver: "Sine 5ths (2 sines an octave and a 5th apart)" },
 { pvs: "Sin2Oct", evolver: "Sine 2 Octave (2 sines, 2 octaves apart)" },
 { pvs: "Sin4Oct", evolver: "Sine 4 Octave (2 sines, 4 Octaves apart)" },
 { pvs: "Saw5th", evolver: "Sawtooth 5ths (2 saws, an octave and a 5th apart)" },
 { pvs: "Saw2Oct", evolver: "Sawtooth 2 Octaves (2 saws, 2 octaves apart)" },
 { pvs: "Sqr5th", evolver: "Square 5ths (2 squares, a 5th apart)" },
 { pvs: "Sqr5Oct", evolver: "Square Octave+5th (2 squares, an octave and a 5th apart)" },
 { pvs: "Sqr2Oct", evolver: "Square 2-Octaves (2 squares, 2 octaves apart)" },
 { pvs: "WarmLo", evolver: "Bell Partials 2" },
 { pvs: "Bells", evolver: "Null (Blank) Wave" },
 { pvs: "*null*", evolver: "?" },
 { pvs: "Noise", evolver: "?" },
];